---
title: "Carryover 2.0"
author: "Kolby Grint"
date: "11/20/2020"
output:
  pdf_document: default
  html_document: default
---


```{r, include= FALSE}
library(car)
library(ggplot2)
library(emmeans)
library(lme4)
library(lmerTest)
library(patchwork)
library(glmmTMB)
library(dplyr)
library(tidyverse)
library(multcomp)
```

```{r}
getwd()

Corn= read.csv(file="Corn_MasterData.csv")
Soybean= read.csv(file="Soybean_MasterData.csv")

CC= read.csv(file= "CoverCropData.csv")

cnyield= data.frame()
sbyield= data.frame()
```


```{r}
Corn1 <- Corn %>% 
  mutate(Rep = as_factor(Rep),
         Year = as_factor(Year),
         Herb = fct_recode(Herb,
                          "Control" = "CTRL",
                          "50% fomesafen"  = "FO50",
                          "25% fomesafen" = "FO25",
                          "50% imazethapyr" = "IM50",
                          "25% imazethapyr" = "IM25"),
         Soil= fct_recode(Soil, 
                          "Cover Crop" = "CC",
                          "No-Till" = "NT",
                          "Tillage" = "Till"),
         Crop.Canopy = round(Crop.Canopy/100, 2),
         yield = round(yield, 5)) %>%
  filter(!is.na(yield)) %>%
  filter(!is.na(Crop.Canopy)) %>%
  filter(!is.na(Stand.Count)) %>%
  janitor::clean_names()

Soybean1 <- Soybean %>% 
  mutate(Rep = as_factor(Rep),
         Year = as_factor(Year),
         Herb = fct_recode(Herb,
                          "Control" = "CTRL",
                          "50% fomesafen"  = "FO50",
                          "25% fomesafen" = "FO25",
                          "50% imazethapyr" = "IM50",
                          "25% imazethapyr" = "IM25"),
         Soil= fct_recode(Soil, 
                          "Cover Crop" = "NT+CC",
                          "No-Till" = "NT",
                          "Tillage" = "Till"),
         Crop.Canopy = round(Crop.Canopy/100, 2),
         yield = round(yield, 4)) %>%
  filter(!is.na(yield)) %>%
  filter(!is.na(Crop.Canopy)) %>%
  filter(!is.na(Stand.Count)) %>%
  janitor::clean_names()

CornCC <- CC %>%
  filter(Crop == "Corn") %>%
  mutate(Rep = as_factor(Rep),
         Year = as_factor(Year),
         Site_Crop_Yr = fct_recode(Site_crop_yr,
                          "Arlington 2019" = "ARL_CN_19",
                          "Arlington 2020"  = "ARL_CN_20",
                          "Havelock 2019" = "HAV_CN_19",
                          "Havelock 2020" = "HAV_CN_20",
                          "Lancaster 2019" = "LAN_CN_19",
                          "Lancaster 2020" = "LAN_CN_20"),
         Canopy = round(Canopy/100, 3)) %>%
  filter(!is.na(Biomass_kg)) %>%
  filter(!is.na(Site_crop_yr)) %>% 
  filter(!Site_crop_yr == "ARL_CN_20") %>%
  janitor::clean_names()

SBCC <- CC %>%
  filter(Crop == "Soybean") %>%
  mutate(Rep = as_factor(Rep),
         Year = as_factor(Year),
         Site_Crop_Yr = fct_recode(Site_Crop_Yr,
                          "Arlington 2019" = "ARL_SB_19",
                          "Arlington 2020"  = "ARL_SB_20",
                          "Havelock 2019" = "HAV_SB_19",
                          "Havelock 2020" = "HAV_SB_20",
                          "Lancaster 2019" = "LAN_SB_19",
                          "Lancaster 2020" = "LAN_SB_20"),
         Canopy = round(Canopy/100, 3)) %>%
  filter(!is.na(Biomass_kg)) %>%
  janitor::clean_names()

order= c("Tillage", "No-Till", "Cover Crop")
```


```{r}
Corn1 %>%
  ggplot(aes(x = soil, y = yield, color = location)) +
  geom_boxplot() +
  facet_grid(crop ~ year)
```

```{r}
Soybean1 %>%
  ggplot(aes(x = soil, y = yield, color = location)) +
  geom_boxplot() +
  facet_grid(crop ~ year)
```

```{r}

```


# Corn Yield

```{r}
arlcn_yield2= lmer(yield~ soil*herb + (1|rep/year), data= (filter(Corn1, location == "Arlington")))

qqnorm(resid(arlcn_yield2))

plot(arlcn_yield2)
#assumptions look good

anova(arlcn_yield2)
```

### Arlington 2019 Analysis ---- We decided to use only this site-year in the paper
```{r}
arlcn_yield1= lmer(yield~ soil*herb + (1|rep:location), data= (filter(Corn1, site_crop_yr == "ARL_CN_19")))

qqnorm(resid(arlcn_yield1))

plot(arlcn_yield1)
#assumptions look good

anova(arlcn_yield1)
#soil managment fixed effect significant
```

### Lancaster Analysis
```{r}
lancn_yield= lmer(yield~ soil*herb + (1|rep/year), data= (filter(Corn1, location == "Lancaster")))

qqnorm(resid(lancn_yield))

plot(lancn_yield)
#assumptions look good

anova(lancn_yield)
#Soil management fixed effect significant
```

### Havelock Analysis
```{r}
havcn_yield= lmer(yield~ soil*herb + (1|rep/year), data= (filter(Corn1, location == "Havelock")))
#from my understanding the "boundary (singular) fit: see ?isSingular" error means that the estimate of error between random effects, in this case rep/year is almost zero, meaning there isn't a lot of random variability?

qqnorm(resid(havcn_yield))

plot(havcn_yield)
#assumptions look good

anova(havcn_yield)
#soil management significant

summary(havcn_yield)

```

```{r}
arl_cn_lsmeans<- lsmeans(arlcn_yield1, ~ soil, contr="pairwise", adjust="none")

arl_cn_cld <- cld(arl_cn_lsmeans$lsmeans, alpha=0.05, Letters=letters, adjust="none", sort=TRUE, reverse=TRUE)

arl_cn_cld <- as_tibble(arl_cn_cld) %>% 
  rename(yield = lsmean) %>%
  mutate(soil= factor(soil, levels= order)) %>%
  arrange(soil)
```

```{r}
lan_cn_lsmeans<- lsmeans(lancn_yield, ~ soil, contr="pairwise", adjust="none")

lan_cn_cld <- cld(lan_cn_lsmeans$lsmeans, alpha=0.05, Letters=letters, adjust="none", sort=TRUE, reverse=TRUE)

lan_cn_cld <- as_tibble(lan_cn_cld) %>% 
  rename(yield = lsmean) %>%
  mutate(soil= factor(soil, levels= order)) %>%
  arrange(soil)
```

```{r}
hav_cn_lsmeans<- lsmeans(havcn_yield, ~ soil, contr="pairwise", adjust="none")

hav_cn_cld <- cld(hav_cn_lsmeans$lsmeans, alpha=0.05, Letters=letters, adjust="none", sort=TRUE, reverse=TRUE)

hav_cn_cld <- as_tibble(hav_cn_cld) %>% 
  rename(yield = lsmean) %>%
  mutate(soil= factor(soil, levels= order)) %>%
  arrange(soil)
```
```{r}
arl_cn_cld$location= c("Arlington")
lan_cn_cld$location= c('Lancaster')
hav_cn_cld$location= c('Havelock')

cnyield<- rbind(arl_cn_cld, cnyield)
cnyield<- rbind(lan_cn_cld, cnyield)
cnyield<- rbind(hav_cn_cld, cnyield)
```

```{r}
Corn1= Corn1 %>%
 filter(site_crop_yr != "ARL_CN_20")

y1<- ggplot(cnyield, aes(x= soil, y= yield, color= soil)) +
  geom_point(size= 3) +
  geom_errorbar(aes(ymin= lower.CL, ymax= upper.CL), width= .3) +
  geom_text(aes(label = .group), nudge_y = 2200) +
  geom_jitter(data = Corn1 ,mapping = aes(y = yield), alpha = 0.2) +
  #coord_flip() +
  facet_grid(~location) +
  theme_bw() +
  scale_color_brewer(palette = "Dark2") +
  theme(legend.position = "none") +
  labs(title = "Corn Yield")


```




# Soybean Yield

### Arlington Analysis
```{r}
arl_sb_yield= lmer(yield~ soil*herb + (1|rep/year), data= (filter(Soybean1, location == "Arlington")))
summary(arl_sb_yield)

qqnorm(resid(arl_sb_yield))

plot(arl_sb_yield)
#assumptions look good

anova(arl_sb_yield)
#Soil management fixed effect significant
```

### Lancaster Analysis
```{r}
lan_sb_yield= lmer(yield~ soil*herb + (1|rep/year), data= (filter(Soybean1, location == "Lancaster")))

qqnorm(resid(lan_sb_yield))

plot(lan_sb_yield)
#assumptions look good

anova(lan_sb_yield)
#Soil management fixed effect significant
```

### Havelock Analysis
```{r}
hav_sb_yield= lmer(yield~ soil*herb + (1|rep/year), data= (filter(Soybean1, location == "Havelock")))

qqnorm(resid(hav_sb_yield))

plot(hav_sb_yield)
#assumptions look good

anova(hav_sb_yield)
#nothing significant
```

```{r}
arl_sb_lsmeans<- lsmeans(arl_sb_yield, ~ soil, contr="pairwise", adjust="none")

arl_sb_cld <- cld(arl_sb_lsmeans$lsmeans, alpha=0.05, Letters=letters, adjust="none", sort=TRUE, reverse=TRUE)

arl_sb_cld <- as_tibble(arl_sb_cld) %>% 
  rename(yield = lsmean) %>%
  mutate(soil= factor(soil, levels= order)) %>%
  arrange(soil)
```

```{r}
lan_sb_lsmeans<- lsmeans(lan_sb_yield, ~ soil, contr="pairwise", adjust="none")

lan_sb_cld <- cld(lan_sb_lsmeans$lsmeans, alpha=0.05, Letters=letters, adjust="none", sort=TRUE, reverse=TRUE)

lan_sb_cld <- as_tibble(lan_sb_cld) %>% 
  rename(yield = lsmean) %>%
  mutate(soil= factor(soil, levels= order)) %>%
  arrange(soil)
```

```{r}
hav_sb_lsmeans<- lsmeans(hav_sb_yield, ~ soil, contr="pairwise", adjust="none")

hav_sb_cld <- cld(hav_sb_lsmeans$lsmeans, alpha=0.05, Letters=letters, adjust="none", sort=TRUE, reverse=TRUE)

hav_sb_cld <- as_tibble(hav_sb_cld) %>% 
  rename(yield = lsmean) %>%
  mutate(soil= factor(soil, levels= order)) %>%
  arrange(soil)
```

```{r}
arl_sb_cld$location= c("Arlington")
lan_sb_cld$location= c('Lancaster')
hav_sb_cld$location= c('Havelock')

sbyield<- rbind(arl_sb_cld, sbyield)
sbyield<- rbind(lan_sb_cld, sbyield)
sbyield<- rbind(hav_sb_cld, sbyield)
```

```{r}
y2<- ggplot(sbyield, aes(x= soil, y= yield, color= soil)) +
  geom_point(size= 3) +
  geom_errorbar(aes(ymin= lower.CL, ymax= upper.CL), width= .3) +
  geom_text(aes(label = .group), nudge_y = 800) +
  geom_jitter(data = Soybean1 ,mapping = aes(y = yield), alpha = 0.2) +
  #coord_flip() +
  facet_grid(~location) +
  theme_bw() +
  scale_color_brewer(palette = "Dark2") +
  theme(legend.position = "none") +
  labs(title = "Soybean Yield")


```





# Cover Crop Biomass analysis
### Corn
```{r}

cn_cc_bio= lmer(biomass_kg~ site_crop_yr * herb + (1|site_crop_yr:rep), data=CornCC)

qqnorm(resid(cn_cc_bio))
plot(cn_cc_bio)
#Assumption for equal variance not met

cn_cc_bio1= lmer(sqrt(biomass_kg)~ site_crop_yr * herb + (1|site_crop_yr:rep), data=CornCC)

qqnorm(resid(cn_cc_bio1))
plot(cn_cc_bio1)
#assumptions improved. Use this one!

anova(cn_cc_bio1)
#Site-year significant
```
### Soybean
```{r}
sb_cc_bio= lmer(biomass_kg~ site_crop_yr * herb + (1|site_crop_yr:rep), data=SBCC)

qqnorm(resid(sb_cc_bio))
plot(sb_cc_bio)
#assumptions for equal variance not met

sb_cc_bio1= lmer(sqrt(biomass_kg)~ site_crop_yr * herb + (1|site_crop_yr:rep), data=SBCC)

qqnorm(resid(sb_cc_bio1))
plot(sb_cc_bio1)
#assumption improved. Maybe clean datapoint

anova(sb_cc_bio1)
#Site-year significant
```

```{r}

```


```{r}

```


# Cover Crop Canopy
### Corn

```{r}
CornCC1 <- CornCC %>%
  filter(!is.na(canopy))
```

```{r}
cn_cc_bio= glmmTMB(canopy~ site_crop_yr*herb + (1|site_crop_yr:rep), data=CornCC1, beta_family(link="logit"))

Anova(cn_cc_bio)
#Site-year significant
```

### Soybean

```{r}
SBCC1 <- SBCC %>%
  filter(!is.na(canopy))
```


```{r}
sb_cc_bio= glmmTMB(canopy~ site_crop_yr*herb + (1|site_crop_yr:rep), data=SBCC, beta_family(link="logit"))

Anova(sb_cc_bio)
#Site-Year significant
```



